spring:
  application:
    name: order-service 
  cloud:
     config:
        override-none: true 
  rabbitmq:
    host: 192.168.216.134
    port: 5672
    username: admin
    password: admin
        
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
server:
  port: 8201
   
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
                
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
---
spring:
  profiles: order1
  
server:
  port: 8201      
---
spring:
  profiles: order2
server:
  port: 8202  
      

